version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command:  ["sh", "/code/web-start.sh"]
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DB_HOST: "postgres"
      DB_NAME: "db_employee"
      DB_USER: "postgres"
      DB_PASS: "postgres"
      DB_PORT: "5432"
      APP_PORT: "8000"
    restart: always
  postgres:
    image: postgres:10.4-alpine
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: db_employee
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /tmp